apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sample-nodejs-app
  name: sample-nodejs-app
  namespace: test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: sample-nodejs-app
status:
  loadBalancer: {}
