name: simple wf 
on: 
  push:
    branches:
      - main


jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: explore the runner machine
      run: |
        pwd
        ls -al
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-nodejs-app:4
    - name: get eks kubeconfig
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name demo
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-2'
    - uses: azure/setup-kubectl@v3
      with:
          version: 'v1.29.5' # default is latest stable
      id: install-kubectl
    - name: test eks access
      run: | 
        kubectl get nodes -o wide
        kubectl create ns test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-2'
    - uses: azure/setup-helm@v4.2.0
      with:
          version: 'v3.8.0' # default is latest (stable)
      id: install-helm

    - name: helm upgrade 
      run: |
        cd helm-chart 
        helm upgrade --install sample-nodejs-app ./sample-nodejs-app
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-2'
    - name: helm list
      run: | 
        helm list
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-2'
