name: simple wf 
on: [workflow_dispatch]


jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: explore the runner machine
      run: |
        pwd
        ls -al
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-nodejs-app:4
    - name: get eks kubeconfig
      run: |
        aws eks update-kubeconfig --region eu-west-2 --name demo
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-2'
    - uses: azure/setup-kubectl@v3
      with:
          version: '1.29.5' # default is latest stable
      id: install
    - name: test eks access
      run: | 
        kubectl get nodes -o wide