name: simple wf 
on: [workflow_dispatch]


jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: explore the runner machine
      run: |
        pwd
        ls -al
      