name: simple wf 
on: [workflow_dispatch]


jobs:
  package-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4
    - name: explore the runner machine
      run: |
        pwd
        ls -al
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sample-nodejs-app:4